# Generated by Django 4.2.1 on 2023-05-21 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trader_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trader",
            name="email",
        ),
        migrations.RemoveField(
            model_name="trader",
            name="password",
        ),
    ]
